### ISSUE TITLE
[Feat]My Pin Modal View 구현

### ISSUE THREAD

**Issue by yungahui** [DeveloperAcademy-POSTECH/chagokchagok#26]
# Describe the Feature
<img width="366" alt="image" src="https://user-images.githubusercontent.com/94831367/173268925-05328355-fa34-42d6-8b7d-ff82374c253d.png">

 # To do
 - [ ] 모달 뷰 구현

# ETC

**Comment by deslog** [comment]
modal view에서 목록으로 보기 버튼으로 변경되었음.
